version: '3'
services: 
  mongodb:
    image: mongo

  web:
    image: demo:latest
    ports: 
      - 80:80

  api:
    image: demo-api:latest
    ports: 
      - 3000:3000
    links: 
      - mongodb:mongodb

  blueocean:
    image: jenkinsci/blueocean
    ports: 
      - 8888:8080
      - 55555:50000
    user: root
    volumes:   
      - /var/run/docker.sock:/var/run/docker.sock
      - /Users/al/Desktop/Develop/JenkinsCI/blueocean/jenkins_home:/var/jenkins_home

  jenkins:
    image: jenkinsci/jenkins
    ports: 
      - 8080:8080
      - 50000:50000
    user: root
    volumes:   
      - /var/run/docker.sock:/var/run/docker.sock
      - /Users/al/Desktop/Develop/JenkinsCI/jenkins/jenkins_home:/var/jenkins_home

      