version: '3'
services: 
  mongodb:
    image: mongo

  web:
    image: demo:latest
    ports: 
      - 80:80

  api:
    image: demo-api:latest
    ports: 
      - 3000:3000
    links: 
      - mongodb:mongodb

  blueocean:
    image: jenkinsci/blueocean
    ports: 
      - 8888:8080
    user: root
    volumes:   
      - /var/run/docker.sock:/var/run/docker.sock

  jenkin:
    image: jenkinsci/jenkin
    ports: 
      - 8080:8080
    user: root
    volumes:   
      - /var/run/docker.sock:/var/run/docker.sock

      