version: '3'
services: 
  jenkins:
    image: jenkinsci/blueocean
    ports: 
      - 8080:8080
      - 50000:50000
    user: root
    volumes:   
      - /var/run/docker.sock:/var/run/docker.sock
      - /Users/al/Desktop/Develop/Jenkins/blueocean/jenkins_home:/var/jenkins_home

  

      